# Use by calling brew bundle -v

# Taps
tap "thoughtbot/formulae"
tap "heroku/brew"

# Brews
brew "fish"
brew "heroku"
brew "neovim"
brew "git"
brew "mas"
brew "neovim"
brew "nmap"
brew "python"
brew "rcm"
brew "tree"

# Casks
cask "1password"
cask "avast-security"
cask "bartender"
cask "docker"
cask "dropbox"
cask "balenaetcher"
cask "firefox"
cask "flux"
cask "gog-galaxy"
cask "jetbrains-toolbox"
cask "little-snitch"
cask "microsoft-office"
cask "parallels"
cask "homebrew/cask-drivers/sonos"
cask "spectacle"
cask "spotify"
cask "steam"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "yubico-authenticator"
